package site.rekadev.rekaqueue.notifier;

import android.Manifest;import android.app.*;import android.content.*;import android.graphics.Color;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import org.json.*;

public class MainActivity extends Activity {
 EditText server,user,password; TextView status,currentNumber,waitingText; Spinner serviceSpinner,counterSpinner; LinearLayout root,operatorPanel; android.content.SharedPreferences prefs; JSONArray serviceData=new JSONArray(),counterData=new JSONArray();int currentTicketId=0;
 int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView text(String s,int size,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(Color.rgb(10,39,75));if(bold)v.setTypeface(null,1);v.setPadding(0,dp(5),0,dp(5));return v;}
 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("reka",MODE_PRIVATE);if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7);
  ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(Color.rgb(239,245,251));root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(24),dp(34),dp(24),dp(28));scroll.addView(root);
  TextView mark=text("RQ",22,true);mark.setTextColor(Color.WHITE);mark.setGravity(17);mark.setBackgroundColor(Color.rgb(255,205,52));root.addView(mark,new LinearLayout.LayoutParams(dp(58),dp(58)));root.addView(text("Reka Queue Notifier",30,true));TextView lead=text("Notifikasi antrean operator tetap aktif tanpa membuka browser.",16,false);lead.setTextColor(Color.rgb(87,108,132));root.addView(lead);
  LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setBackgroundResource(site.rekadev.rekaqueue.notifier.R.drawable.panel);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(28),0,0);root.addView(card,cp);
  server=field(card,"Alamat server",prefs.getString("server","http://192.168.12.68:8090"),InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);user=field(card,"Username operator",prefs.getString("username",""),InputType.TYPE_CLASS_TEXT);password=field(card,"Password (tidak disimpan)","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);
  Button connect=new Button(this);connect.setText("HUBUNGKAN PERANGKAT");connect.setTextColor(Color.WHITE);connect.setTextSize(15);connect.setTypeface(null,1);connect.setBackgroundColor(Color.rgb(22,119,200));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(56));bp.setMargins(0,dp(18),0,0);card.addView(connect,bp);status=text(prefs.contains("token")?"Perangkat sudah terhubung.":"Masukkan akun operator untuk mulai.",14,false);card.addView(status);connect.setOnClickListener(new View.OnClickListener(){public void onClick(View v){register();}});
  Button open=new Button(this);open.setText("BUKA KONSOL WEB");root.addView(open,new LinearLayout.LayoutParams(-1,dp(54)));open.setOnClickListener(new View.OnClickListener(){public void onClick(View v){String s=server.getText().toString().trim().replaceAll("/+$","");startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(s+"/operator")));}});if(prefs.contains("token"))buildOperator();setContentView(scroll);
 }
 EditText field(LinearLayout p,String label,String value,int type){p.addView(text(label,14,true));EditText e=new EditText(this);e.setText(value);e.setTextSize(16);e.setSingleLine(true);e.setInputType(type);e.setPadding(dp(14),0,dp(14),0);p.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));return e;}
 void register(){final String s=server.getText().toString().trim().replaceAll("/+$","");final String u=user.getText().toString().trim(),pw=password.getText().toString();if(s.isEmpty()||u.isEmpty()||pw.isEmpty()){status.setText("Semua kolom wajib diisi.");return;}status.setText("Menghubungkan…");new Thread(new Runnable(){public void run(){try{String device=Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID);String body="username="+URLEncoder.encode(u,"UTF-8")+"&password="+URLEncoder.encode(pw,"UTF-8")+"&device_id="+URLEncoder.encode(device,"UTF-8")+"&device_name="+URLEncoder.encode(Build.MANUFACTURER+" "+Build.MODEL+" (Android)","UTF-8");JSONObject d=api(s+"/api/client/notifications/register",body,null).getJSONObject("data");prefs.edit().putString("server",s).putString("username",u).putString("token",d.getString("token")).putLong("cursor",d.optLong("cursor",0)).apply();runOnUiThread(new Runnable(){public void run(){password.setText("");status.setText("Terhubung sebagai "+d.optString("operator",u)+". Notifikasi aktif.");QueueService.start(MainActivity.this);buildOperator();}});}catch(final Exception e){runOnUiThread(new Runnable(){public void run(){status.setText("Gagal: "+e.getMessage());}});}}}).start();}
 void buildOperator(){if(operatorPanel!=null)return;operatorPanel=new LinearLayout(this);operatorPanel.setOrientation(LinearLayout.VERTICAL);operatorPanel.setBackgroundResource(R.drawable.panel);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,-2);pp.setMargins(0,dp(24),0,dp(24));root.addView(operatorPanel,pp);operatorPanel.addView(text("Konsol operator",25,true));operatorPanel.addView(text("Layanan",13,true));serviceSpinner=new Spinner(this);operatorPanel.addView(serviceSpinner,new LinearLayout.LayoutParams(-1,dp(52)));operatorPanel.addView(text("Loket",13,true));counterSpinner=new Spinner(this);operatorPanel.addView(counterSpinner,new LinearLayout.LayoutParams(-1,dp(52)));waitingText=text("Menunggu: —",17,true);operatorPanel.addView(waitingText);currentNumber=text("— — —",44,true);currentNumber.setGravity(17);currentNumber.setTextColor(Color.rgb(22,119,200));operatorPanel.addView(currentNumber,new LinearLayout.LayoutParams(-1,dp(100)));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);operatorPanel.addView(actions);button(actions,"PANGGIL ULANG","recall");button(actions,"BERIKUTNYA","next");LinearLayout states=new LinearLayout(this);states.setOrientation(LinearLayout.HORIZONTAL);operatorPanel.addView(states);button(states,"LAYANI","serve");button(states,"SELESAI","complete");button(states,"LEWATI","skip");serviceSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int x,long id){refreshState();}});counterSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int x,long id){refreshState();}});loadOperator();}
 void button(LinearLayout row,String label,final String action){Button b=new Button(this);b.setText(label);b.setTextSize(12);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(54),1);p.setMargins(dp(2),dp(4),dp(2),dp(4));row.addView(b,p);b.setOnClickListener(new View.OnClickListener(){public void onClick(View v){operatorAction(action);}});}
 int selectedId(JSONArray a,Spinner s){if(s==null||a.length()==0)return 0;return a.optJSONObject(s.getSelectedItemPosition()).optInt("id");}
 void loadOperator(){new Thread(new Runnable(){public void run(){try{JSONObject d=api(base()+"/api/client/operator-state",null,token()).getJSONObject("data");serviceData=d.getJSONArray("services");counterData=d.getJSONArray("counters");final java.util.ArrayList<String> ss=new java.util.ArrayList<String>(),cc=new java.util.ArrayList<String>();for(int i=0;i<serviceData.length();i++)ss.add(serviceData.getJSONObject(i).getString("name"));for(int i=0;i<counterData.length();i++)cc.add(counterData.getJSONObject(i).getString("name"));runOnUiThread(new Runnable(){public void run(){serviceSpinner.setAdapter(new ArrayAdapter<String>(MainActivity.this,android.R.layout.simple_spinner_dropdown_item,ss));counterSpinner.setAdapter(new ArrayAdapter<String>(MainActivity.this,android.R.layout.simple_spinner_dropdown_item,cc));refreshState();}});}catch(final Exception e){showError(e);}}}).start();}
 void refreshState(){if(serviceData.length()==0||counterData.length()==0)return;final int sid=selectedId(serviceData,serviceSpinner),cid=selectedId(counterData,counterSpinner);new Thread(new Runnable(){public void run(){try{final JSONObject d=api(base()+"/api/client/operator-state?service_id="+sid+"&counter_id="+cid,null,token()).getJSONObject("data");runOnUiThread(new Runnable(){public void run(){waitingText.setText("Menunggu: "+d.optInt("waiting"));JSONObject c=d.optJSONObject("current");currentTicketId=c==null?0:c.optInt("id");currentNumber.setText(c==null?"— — —":c.optString("ticket_number"));}});}catch(Exception e){showError(e);}}}).start();}
 void operatorAction(final String action){final int sid=selectedId(serviceData,serviceSpinner),cid=selectedId(counterData,counterSpinner);if(!action.equals("next")&&currentTicketId==0){Toast.makeText(this,"Belum ada antrean aktif.",Toast.LENGTH_SHORT).show();return;}new Thread(new Runnable(){public void run(){try{String body="action="+action+"&service_id="+sid+"&counter_id="+cid+"&ticket_id="+currentTicketId;final JSONObject r=api(base()+"/api/client/operator-action",body,token());runOnUiThread(new Runnable(){public void run(){JSONObject d=r.optJSONObject("data");if(d==null){Toast.makeText(MainActivity.this,"Tidak ada antrean menunggu.",Toast.LENGTH_SHORT).show();}refreshState();}});}catch(Exception e){showError(e);}}}).start();}
 String base(){return prefs.getString("server","");}String token(){return prefs.getString("token","");}void showError(final Exception e){runOnUiThread(new Runnable(){public void run(){Toast.makeText(MainActivity.this,e.getMessage(),Toast.LENGTH_LONG).show();}});}
 static JSONObject api(String url,String body,String token)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(15000);c.setRequestProperty("Accept","application/json");if(token!=null)c.setRequestProperty("X-Device-Token",token);if(body!=null){c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/x-www-form-urlencoded");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes("UTF-8"));}}InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();JSONObject r=new JSONObject(read(in));if(c.getResponseCode()>=400)throw new Exception(r.optString("error","Server error"));return r;}
 static String read(InputStream in)throws IOException{BufferedReader b=new BufferedReader(new InputStreamReader(in));StringBuilder s=new StringBuilder();String l;while((l=b.readLine())!=null)s.append(l);return s.toString();}
}
