package site.rekadev.rekaqueue.notifier;
import android.app.*;import android.content.*;import android.os.*;import android.media.*;import java.io.*;import java.net.*;import org.json.*;
public class QueueService extends Service{
 static final String SERVICE="reka_service",ALERT="reka_alert",STOP_SOUND="site.rekadev.rekaqueue.STOP_SOUND";static MediaPlayer activePlayer;volatile boolean running=true;android.content.SharedPreferences prefs;
 public static void start(Context c){Intent i=new Intent(c,QueueService.class);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 public static void stopSound(Context c){Intent i=new Intent(c,QueueService.class).setAction(STOP_SOUND);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 public void onCreate(){super.onCreate();prefs=getSharedPreferences("reka",MODE_PRIVATE);NotificationManager n=getSystemService(NotificationManager.class);if(Build.VERSION.SDK_INT>=26){n.createNotificationChannel(new NotificationChannel(SERVICE,"Reka Queue service",NotificationManager.IMPORTANCE_LOW));NotificationChannel alerts=new NotificationChannel(ALERT,"Antrean baru",NotificationManager.IMPORTANCE_HIGH);alerts.setSound(null,null);n.createNotificationChannel(alerts);}Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);startForeground(101,new Notification.Builder(this,Build.VERSION.SDK_INT>=26?SERVICE:null).setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("Reka Queue aktif").setContentText("Menunggu antrean baru").setContentIntent(pi).build());new Thread(new Runnable(){public void run(){poll();}}).start();}
 public int onStartCommand(Intent i,int f,int id){if(i!=null&&STOP_SOUND.equals(i.getAction()))stopSoundInternal();return START_STICKY;}public android.os.IBinder onBind(Intent i){return null;}public void onDestroy(){running=false;stopSoundInternal();super.onDestroy();}
 void poll(){int errors=0;while(running){try{String token=prefs.getString("token","");if(token.isEmpty()){stopSelf();return;}long cursor=prefs.getLong("cursor",0);HttpURLConnection c=(HttpURLConnection)new URL(prefs.getString("server","")+"/api/client/notifications?after="+cursor).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(15000);c.setRequestProperty("X-Device-Token",token);if(c.getResponseCode()==401){alert("Sesi perangkat berakhir","Buka aplikasi dan hubungkan ulang.",(int)System.currentTimeMillis());stopSelf();return;}JSONObject data=new JSONObject(MainActivity.read(c.getInputStream()));JSONObject settings=data.optJSONObject("settings");boolean enabled=settings==null||settings.optBoolean("enabled",true);JSONArray tickets=data.optJSONArray("tickets");if(enabled&&tickets!=null)for(int x=0;x<tickets.length();x++){JSONObject t=tickets.getJSONObject(x);alert("Antrean baru · "+t.optString("service_name"),t.optString("ticket_number")+" menunggu dipanggil",t.optInt("id",200+x));playSound(settings);}prefs.edit().putLong("cursor",data.optLong("cursor",cursor)).apply();errors=0;Thread.sleep(1000);}catch(Exception e){errors++;try{Thread.sleep(Math.min(60000,errors*4000L));}catch(InterruptedException ignored){}}}}
 synchronized void stopSoundInternal(){if(activePlayer!=null){try{activePlayer.stop();}catch(Exception ignored){}try{activePlayer.release();}catch(Exception ignored){}activePlayer=null;}}
 void playSound(JSONObject settings){try{float volume=(float)(settings==null ? .8 : settings.optDouble("volume",.8));String type=settings==null?"chime":settings.optString("sound_type","chime"),sound=settings==null?"":settings.optString("sound_url","");if(!type.equals("custom")||sound.isEmpty()){if(!type.equals("bell")&&!type.equals("beep"))type="chime";sound="/assets/sounds/"+type+".wav";}if(sound.startsWith("/"))sound=prefs.getString("server","")+sound;sound+=(sound.contains("?")?"&":"?")+"android_audio="+System.currentTimeMillis();stopSoundInternal();final MediaPlayer p=new MediaPlayer();activePlayer=p;p.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_NOTIFICATION_RINGTONE).setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION).build());p.setDataSource(sound);p.setVolume(volume,volume);p.setOnPreparedListener(new MediaPlayer.OnPreparedListener(){public void onPrepared(MediaPlayer m){synchronized(QueueService.this){if(m==activePlayer)m.start();else m.release();}}});p.setOnCompletionListener(new MediaPlayer.OnCompletionListener(){public void onCompletion(MediaPlayer m){synchronized(QueueService.this){if(m==activePlayer)activePlayer=null;}m.release();}});p.prepareAsync();}catch(Exception ignored){stopSoundInternal();}}
 void alert(String title,String body,int id){Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,id,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Intent stop=new Intent(this,QueueService.class).setAction(STOP_SOUND);PendingIntent stopPi=PendingIntent.getService(this,id+100000,stop,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=new Notification.Builder(this,Build.VERSION.SDK_INT>=26?ALERT:null).setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(title).setContentText(body).setAutoCancel(true).setContentIntent(pi).setCategory(Notification.CATEGORY_CALL).setPriority(Notification.PRIORITY_MAX).addAction(android.R.drawable.ic_lock_silent_mode,"Hentikan suara",stopPi);getSystemService(NotificationManager.class).notify(id,b.build());}
}
