<?php
declare(strict_types=1);
define('ABSPATH',__DIR__);
$GLOBALS['wp_mock_method']='GET';
function add_action(...$a){} function add_shortcode(...$a){} function add_options_page(...$a){} function register_setting(...$a){} function wp_register_style(...$a){} function wp_enqueue_style(...$a){}
function plugins_url($path,$file){return '/wp-content/plugins/reka-queue-online/'.$path;} function shortcode_atts($defaults,$attrs,$tag){return array_merge($defaults,$attrs);} function get_option($key,$default=[]){return ['server_url'=>'http://queue.test','api_key'=>'secret','privacy_url'=>'https://example.test/privacy'];} function wp_parse_args($a,$b){return array_merge($b,$a);} function esc_url_raw($v){return filter_var($v,FILTER_SANITIZE_URL);} function sanitize_text_field($v){return trim(strip_tags((string)$v));} function sanitize_email($v){return filter_var((string)$v,FILTER_SANITIZE_EMAIL);} function sanitize_textarea_field($v){return trim(strip_tags((string)$v));} function wp_unslash($v){return $v;} function wp_json_encode($v){return json_encode($v);} function is_wp_error($v){return false;} function wp_remote_retrieve_response_code($v){return $v['status'];} function wp_remote_retrieve_body($v){return $v['body'];} function wp_verify_nonce($v,$action){return $v==='valid';} function wp_nonce_field($action,$name,$referer=true,$echo=true){return '<input type="hidden" name="'.$name.'" value="valid">';} function wp_date($format,$time=null){return date($format,$time??time());} function esc_html($v){return htmlspecialchars((string)$v,ENT_QUOTES);} function esc_attr($v){return htmlspecialchars((string)$v,ENT_QUOTES);} function esc_url($v){return htmlspecialchars((string)$v,ENT_QUOTES);} function current_user_can($v){return true;} function settings_fields($v){} function submit_button($v){} function esc_js($v){return addslashes($v);} function wp_create_nonce($v){return 'valid';} function check_ajax_referer($v){} function wp_send_json_success($v){throw new RuntimeException('success:'.$v['message']);} function wp_send_json_error($v,$s=400){throw new RuntimeException('error:'.$v['message']);}
function wp_remote_request($url,$args){$method=$args['method'];if($method==='GET'&&str_ends_with($url,'/api/public/services'))return ['status'=>200,'body'=>json_encode(['data'=>[['id'=>2,'name'=>'Pendaftaran']]])];if($method==='POST'&&str_ends_with($url,'/api/public/registrations'))return ['status'=>201,'body'=>json_encode(['data'=>['registration_code'=>'RQ-TEST1234','visitor_name'=>'Budi','service_name'=>'Pendaftaran','visit_date'=>date('Y-m-d')]])];if($method==='POST'&&str_ends_with($url,'/api/public/check-in'))return ['status'=>200,'body'=>json_encode(['data'=>['ticket_number'=>'B-001','service_name'=>'Pendaftaran']])];return ['status'=>404,'body'=>'{"error":"not found"}'];}
require dirname(__DIR__).'/integrations/wordpress/reka-queue-online/reka-queue-online.php';
function ok($condition,$message){if(!$condition)throw new RuntimeException($message);}
$html=Reka_Queue_Online::registrationForm(['service'=>'Pendaftaran']);ok(str_contains($html,'Pendaftaran Antrean Online'),'Registration form missing');ok(str_contains($html,'value="2" selected'),'Service preselection failed');ok(!str_contains($html,'secret'),'API key leaked into HTML');
$_SERVER['REQUEST_METHOD']='POST';$_POST=['reka_queue_action'=>'register','reka_queue_nonce'=>'valid','service_id'=>'4','visitor_name'=>'Budi','visit_date'=>date('Y-m-d'),'consent'=>'1'];$html=Reka_Queue_Online::registrationForm();ok(str_contains($html,'RQ-TEST1234'),'Registration result missing');
$_POST=['reka_queue_action'=>'checkin','reka_queue_nonce'=>'valid','registration_code'=>'RQ-TEST1234'];$html=Reka_Queue_Online::checkinForm();ok(str_contains($html,'B-001'),'Check-in result missing');ok(!str_contains($html,'secret'),'API key leaked from check-in HTML');
echo "WordPress plugin runtime: 6 assertions passed.\n";
