<?php
/**
 * Plugin Name: Reka Queue Online
 * Description: Formulir pendaftaran dan check-in online untuk Reka Queue Management.
 * Version: 1.0.0
 * Author: Sulis Setiyawan — rekakarsa
 * License: GPL-2.0-or-later
 * Text Domain: reka-queue-online
 */
defined('ABSPATH') || exit;

final class Reka_Queue_Online
{
    private const OPTION='reka_queue_online_settings';
    public static function boot(): void {add_action('admin_menu',[self::class,'menu']);add_action('admin_init',[self::class,'settings']);add_action('wp_enqueue_scripts',[self::class,'assets']);add_shortcode('reka_queue_form',[self::class,'registrationForm']);add_shortcode('reka_queue_checkin',[self::class,'checkinForm']);add_action('wp_ajax_reka_queue_test',[self::class,'testConnection']);}
    public static function menu(): void {add_options_page('Reka Queue','Reka Queue','manage_options','reka-queue-online',[self::class,'settingsPage']);}
    public static function settings(): void {register_setting('reka_queue_online',self::OPTION,['sanitize_callback'=>[self::class,'sanitize']]);}
    public static function sanitize(array $input): array {return ['server_url'=>esc_url_raw(rtrim((string)($input['server_url']??''),'/')),'api_key'=>sanitize_text_field((string)($input['api_key']??'')),'privacy_url'=>esc_url_raw((string)($input['privacy_url']??''))];}
    public static function assets(): void {wp_register_style('reka-queue-online',plugins_url('assets/reka-queue.css',__FILE__),[], '1.0.0');}
    private static function config(): array {return wp_parse_args((array)get_option(self::OPTION,[]),['server_url'=>'','api_key'=>'','privacy_url'=>'']);}
    private static function api(string $method,string $path,?array $body=null): array
    {
        $config=self::config();if(!$config['server_url']||!$config['api_key'])throw new RuntimeException('Integrasi antrean belum dikonfigurasi oleh administrator website.');
        $args=['method'=>$method,'timeout'=>15,'redirection'=>2,'headers'=>['Accept'=>'application/json','X-API-Key'=>$config['api_key']]];if($body!==null){$args['headers']['Content-Type']='application/json';$args['body']=wp_json_encode($body);}
        $response=wp_remote_request($config['server_url'].$path,$args);if(is_wp_error($response))throw new RuntimeException('Server antrean tidak dapat dihubungi: '.$response->get_error_message());$status=(int)wp_remote_retrieve_response_code($response);$decoded=json_decode((string)wp_remote_retrieve_body($response),true);if(!is_array($decoded))throw new RuntimeException('Respons server antrean tidak valid.');if($status<200||$status>=300)throw new RuntimeException(sanitize_text_field((string)($decoded['error']??'Permintaan antrean gagal.')));return (array)($decoded['data']??$decoded);
    }
    public static function registrationForm(array $attributes=[]): string
    {
        wp_enqueue_style('reka-queue-online');$attributes=shortcode_atts(['service'=>''], $attributes,'reka_queue_form');$error='';$result=null;
        try{$services=self::api('GET','/api/public/services');}catch(Throwable $e){$services=[];$error=$e->getMessage();}
        if(($_SERVER['REQUEST_METHOD']??'')==='POST'&&isset($_POST['reka_queue_action'])&&$_POST['reka_queue_action']==='register'){
            try{if(!isset($_POST['reka_queue_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['reka_queue_nonce'])),'reka_queue_register'))throw new RuntimeException('Sesi formulir telah berakhir. Muat ulang halaman.');$payload=['service_id'=>(int)($_POST['service_id']??0),'visitor_name'=>sanitize_text_field(wp_unslash($_POST['visitor_name']??'')),'phone'=>sanitize_text_field(wp_unslash($_POST['phone']??'')),'email'=>sanitize_email(wp_unslash($_POST['email']??'')),'identity_number'=>sanitize_text_field(wp_unslash($_POST['identity_number']??'')),'notes'=>sanitize_textarea_field(wp_unslash($_POST['notes']??'')),'visit_date'=>sanitize_text_field(wp_unslash($_POST['visit_date']??'')),'consent'=>isset($_POST['consent'])];$result=self::api('POST','/api/public/registrations',$payload);}catch(Throwable $e){$error=$e->getMessage();}
        }
        ob_start();?><div class="reka-queue-wrap"><?php if($result):?><section class="reka-queue-result" role="status"><span class="reka-success">✓</span><p>PENDAFTARAN BERHASIL</p><h2><?=esc_html($result['registration_code']??'')?></h2><dl><div><dt>Nama</dt><dd><?=esc_html($result['visitor_name']??'')?></dd></div><div><dt>Layanan</dt><dd><?=esc_html($result['service_name']??'')?></dd></div><div><dt>Tanggal</dt><dd><?=esc_html(self::displayDate($result['visit_date']??''))?></dd></div></dl><aside><b>Simpan kode ini.</b> Gunakan untuk check-in pada tanggal kunjungan. Kode ini belum merupakan nomor antrean.</aside><button type="button" onclick="window.print()">Cetak / Simpan</button></section><?php else:?><form method="post" class="reka-queue-form"><h2>Pendaftaran Antrean Online</h2><p>Nomor antrean diberikan setelah check-in pada hari kunjungan.</p><?php if($error):?><div class="reka-error" role="alert"><?=esc_html($error)?></div><?php endif?><?=wp_nonce_field('reka_queue_register','reka_queue_nonce',true,false)?><input type="hidden" name="reka_queue_action" value="register"><div class="reka-grid"><label>Layanan<select name="service_id" required><option value="">Pilih layanan</option><?php foreach($services as $service):$selected=$attributes['service']!==''&&(strcasecmp((string)$attributes['service'],(string)($service['name']??''))===0||strcasecmp((string)$attributes['service'],(string)($service['id']??''))===0);?><option value="<?=esc_attr($service['id'])?>" <?=$selected?'selected':''?>><?=esc_html($service['name'])?></option><?php endforeach?></select></label><label>Tanggal kunjungan<input type="date" name="visit_date" min="<?=esc_attr(wp_date('Y-m-d'))?>" value="<?=esc_attr(wp_date('Y-m-d'))?>" required></label><label>Nama lengkap<input name="visitor_name" minlength="2" maxlength="120" autocomplete="name" required></label><label>Nomor telepon<input name="phone" maxlength="30" autocomplete="tel" inputmode="tel"></label><label>Email <small>(opsional)</small><input type="email" name="email" maxlength="190" autocomplete="email"></label><label>Nomor identitas <small>(opsional)</small><input name="identity_number" maxlength="80"></label></div><label>Keperluan <small>(opsional)</small><textarea name="notes" maxlength="2000" rows="3"></textarea></label><label class="reka-consent"><input type="checkbox" name="consent" value="1" required><span>Saya menyetujui penggunaan data untuk pendaftaran dan pelayanan antrean.<?php $privacy=self::config()['privacy_url'];if($privacy):?> <a href="<?=esc_url($privacy)?>" target="_blank" rel="noopener">Kebijakan privasi</a><?php endif?></span></label><button type="submit">Kirim pendaftaran</button></form><?php endif?></div><?php return (string)ob_get_clean();
    }
    public static function checkinForm(): string
    {
        wp_enqueue_style('reka-queue-online');$error='';$result=null;if(($_SERVER['REQUEST_METHOD']??'')==='POST'&&isset($_POST['reka_queue_action'])&&$_POST['reka_queue_action']==='checkin'){try{if(!isset($_POST['reka_queue_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['reka_queue_nonce'])),'reka_queue_checkin'))throw new RuntimeException('Sesi formulir telah berakhir. Muat ulang halaman.');$code=strtoupper(sanitize_text_field(wp_unslash($_POST['registration_code']??'')));$result=self::api('POST','/api/public/check-in',['registration_code'=>$code]);}catch(Throwable $e){$error=$e->getMessage();}}
        ob_start();?><div class="reka-queue-wrap"><section class="reka-queue-form reka-compact"><?php if($result):?><div class="reka-queue-result" role="status"><span class="reka-success">✓</span><p>CHECK-IN BERHASIL</p><h2><?=esc_html($result['ticket_number']??'')?></h2><aside><b><?=esc_html($result['service_name']??'')?></b><br>Nomor Anda sudah masuk antrean. Mohon menunggu panggilan.</aside></div><?php else:?><h2>Check-in Antrean</h2><p>Masukkan kode pendaftaran online Anda.</p><?php if($error):?><div class="reka-error" role="alert"><?=esc_html($error)?></div><?php endif?><form method="post"><?=wp_nonce_field('reka_queue_checkin','reka_queue_nonce',true,false)?><input type="hidden" name="reka_queue_action" value="checkin"><label>Kode pendaftaran<input name="registration_code" placeholder="RQ-XXXXXXXX" pattern="RQ-[A-Za-z0-9]{8}" maxlength="11" required></label><button type="submit">Check-in sekarang</button></form><?php endif?></section></div><?php return (string)ob_get_clean();
    }
    public static function settingsPage(): void {if(!current_user_can('manage_options'))return;$config=self::config();?><div class="wrap"><h1>Reka Queue Online</h1><p>Hubungkan website ini dengan server Reka Queue Management.</p><form method="post" action="options.php"><?php settings_fields('reka_queue_online');?><table class="form-table"><tr><th><label for="reka-server">URL server</label></th><td><input class="regular-text" id="reka-server" type="url" name="<?=esc_attr(self::OPTION)?>[server_url]" value="<?=esc_attr($config['server_url'])?>" placeholder="http://192.168.1.10:8090" required><p class="description">Tanpa garis miring di akhir.</p></td></tr><tr><th><label for="reka-key">API key</label></th><td><input class="regular-text" id="reka-key" type="password" name="<?=esc_attr(self::OPTION)?>[api_key]" value="<?=esc_attr($config['api_key'])?>" autocomplete="new-password" required></td></tr><tr><th><label for="reka-privacy">URL kebijakan privasi</label></th><td><input class="regular-text" id="reka-privacy" type="url" name="<?=esc_attr(self::OPTION)?>[privacy_url]" value="<?=esc_attr($config['privacy_url'])?>"></td></tr></table><?php submit_button('Simpan pengaturan');?></form><hr><h2>Uji koneksi</h2><p><button class="button" id="reka-test">Test connection</button> <span id="reka-test-result"></span></p><h2>Shortcode</h2><p><code>[reka_queue_form]</code> formulir semua layanan</p><p><code>[reka_queue_form service="DAPODIK"]</code> formulir dengan layanan bawaan</p><p><code>[reka_queue_checkin]</code> formulir check-in</p></div><script>document.getElementById('reka-test').addEventListener('click',async function(){const out=document.getElementById('reka-test-result');out.textContent='Testing…';const body=new URLSearchParams({action:'reka_queue_test',_ajax_nonce:'<?=esc_js(wp_create_nonce('reka_queue_test'))?>'});try{const response=await fetch(ajaxurl,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await response.json();out.textContent=data.data?.message||'Connection failed';out.style.color=data.success?'green':'#b42318'}catch(e){out.textContent='Connection failed'}});</script><?php }
    public static function testConnection(): void {check_ajax_referer('reka_queue_test');if(!current_user_can('manage_options'))wp_send_json_error(['message'=>'Unauthorized'],403);try{$services=self::api('GET','/api/public/services');wp_send_json_success(['message'=>'Connected · '.count($services).' services found']);}catch(Throwable $e){wp_send_json_error(['message'=>$e->getMessage()],422);}}
    private static function displayDate(string $date): string {$time=strtotime($date);return $time?wp_date('d/m/Y',$time):$date;}
}
Reka_Queue_Online::boot();
