CREATE TABLE IF NOT EXISTS settings (
  `key` VARCHAR(100) PRIMARY KEY, `value` TEXT NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS services (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, code VARCHAR(10) NOT NULL UNIQUE,
  description VARCHAR(255), color VARCHAR(20) DEFAULT '#2563eb', daily_limit INT NULL, avg_service_minutes INT NOT NULL DEFAULT 5,
  active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS counters (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, code VARCHAR(20) NOT NULL UNIQUE,
  active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS counter_services (
  counter_id BIGINT UNSIGNED NOT NULL, service_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(counter_id, service_id),
  FOREIGN KEY(counter_id) REFERENCES counters(id) ON DELETE CASCADE, FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL, role ENUM('super_admin','admin','operator') NOT NULL DEFAULT 'operator',
  assigned_counter_id BIGINT UNSIGNED NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(assigned_counter_id) REFERENCES counters(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS daily_sequences (
  service_id BIGINT UNSIGNED NOT NULL, queue_date DATE NOT NULL, last_number INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(service_id, queue_date), FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(36) NOT NULL UNIQUE, service_id BIGINT UNSIGNED NOT NULL,
  counter_id BIGINT UNSIGNED NULL, queue_date DATE NOT NULL, sequence_number INT UNSIGNED NOT NULL, ticket_number VARCHAR(30) NOT NULL,
  status ENUM('waiting','called','serving','completed','skipped','cancelled','transferred') NOT NULL DEFAULT 'waiting',
  called_at DATETIME NULL, service_started_at DATETIME NULL, completed_at DATETIME NULL, cancel_reason VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_daily_ticket(service_id, queue_date, sequence_number), INDEX idx_queue(service_id, queue_date, status, sequence_number),
  FOREIGN KEY(service_id) REFERENCES services(id), FOREIGN KEY(counter_id) REFERENCES counters(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS queue_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, ticket_id BIGINT UNSIGNED NOT NULL, event_type VARCHAR(30) NOT NULL,
  counter_id BIGINT UNSIGNED NULL, user_id BIGINT UNSIGNED NULL, payload JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_events_created(id, created_at), FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
  FOREIGN KEY(counter_id) REFERENCES counters(id) ON DELETE SET NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL,
  entity_type VARCHAR(80) NOT NULL, entity_id BIGINT UNSIGNED NULL, details JSON NULL, ip_address VARCHAR(45) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_audit_created(created_at), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

