#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <wincred.h>
#include <shlobj.h>
#include <stdio.h>
#include <string.h>

static void remove_tree_after_restart(const char *directory){char self[MAX_PATH],path[MAX_PATH];GetModuleFileNameA(NULL,self,MAX_PATH);const char *files[]={"RekaQueueNotifier.exe","reka-notifier.ini","README.txt","RekaQueueNotifier.lnk",NULL};for(int i=0;files[i];i++){snprintf(path,sizeof(path),"%s\\%s",directory,files[i]);DeleteFileA(path);}MoveFileExA(self,NULL,MOVEFILE_DELAY_UNTIL_REBOOT);MoveFileExA(directory,NULL,MOVEFILE_DELAY_UNTIL_REBOOT);}
static void remove_credential(const char *ini){char server[512],username[128],target[800];GetPrivateProfileStringA("notifier","SERVER_URL","",server,sizeof(server),ini);GetPrivateProfileStringA("notifier","USERNAME","",username,sizeof(username),ini);if(server[0]&&username[0]){size_t n=strlen(server);while(n&&server[n-1]=='/')server[--n]=0;snprintf(target,sizeof(target),"RekaQueueNotifier:%s:%s",server,username);CredDeleteA(target,CRED_TYPE_GENERIC,0);}}
int WINAPI WinMain(HINSTANCE instance,HINSTANCE previous,LPSTR command_line,int show){(void)instance;(void)previous;(void)command_line;(void)show;if(MessageBoxA(NULL,"Remove Reka Queue Notifier, its settings, startup entry, and saved device login?","Uninstall Reka Queue Notifier",MB_YESNO|MB_ICONQUESTION)!=IDYES)return 0;HWND running=FindWindowExA(HWND_MESSAGE,NULL,"RekaQueueNotifierWindow",NULL);if(running)SendMessageA(running,WM_CLOSE,0,0);Sleep(500);char directory[MAX_PATH],self[MAX_PATH],ini[MAX_PATH];GetModuleFileNameA(NULL,self,MAX_PATH);strncpy(directory,self,sizeof(directory)-1);directory[sizeof(directory)-1]=0;char *slash=strrchr(directory,'\\');if(slash)*slash=0;snprintf(ini,sizeof(ini),"%s\\reka-notifier.ini",directory);remove_credential(ini);HKEY key;if(RegOpenKeyExA(HKEY_CURRENT_USER,"Software\\Microsoft\\Windows\\CurrentVersion\\Run",0,KEY_SET_VALUE,&key)==ERROR_SUCCESS){RegDeleteValueA(key,"RekaQueueNotifier");RegCloseKey(key);}RegDeleteKeyA(HKEY_CURRENT_USER,"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\RekaQueueNotifier");char programs[MAX_PATH],link[MAX_PATH];if(SHGetFolderPathA(NULL,CSIDL_PROGRAMS,NULL,SHGFP_TYPE_CURRENT,programs)==S_OK){snprintf(link,sizeof(link),"%s\\Reka Queue Notifier.lnk",programs);DeleteFileA(link);}remove_tree_after_restart(directory);MessageBoxA(NULL,"Reka Queue Notifier has been removed.","Uninstall complete",MB_OK|MB_ICONINFORMATION);return 0;}
