#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <shellapi.h>
#include <shlobj.h>
#include <objbase.h>
#include <stdio.h>
#include <string.h>

#define RES_NOTIFIER 101
#define RES_UNINSTALL 102
#define RES_INI 103
#define RES_README 104

static int extract_resource(HINSTANCE instance,int resource_id,const char *target,int preserve){if(preserve&&GetFileAttributesA(target)!=INVALID_FILE_ATTRIBUTES)return 1;HRSRC resource=FindResourceA(instance,MAKEINTRESOURCEA(resource_id),RT_RCDATA);if(!resource)return 0;HGLOBAL loaded=LoadResource(instance,resource);DWORD size=SizeofResource(instance,resource);void *data=LockResource(loaded);HANDLE file=CreateFileA(target,GENERIC_WRITE,0,NULL,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,NULL);if(file==INVALID_HANDLE_VALUE)return 0;DWORD written=0;BOOL ok=WriteFile(file,data,size,&written,NULL);CloseHandle(file);return ok&&written==size;}
static int create_shortcut(const char *target,const char *working_directory,const char *link_path,const char *description){IShellLinkA *link=NULL;IPersistFile *persist=NULL;HRESULT result=CoCreateInstance(&CLSID_ShellLink,NULL,CLSCTX_INPROC_SERVER,&IID_IShellLinkA,(void**)&link);if(FAILED(result))return 0;link->lpVtbl->SetPath(link,target);link->lpVtbl->SetWorkingDirectory(link,working_directory);link->lpVtbl->SetDescription(link,description);result=link->lpVtbl->QueryInterface(link,&IID_IPersistFile,(void**)&persist);if(SUCCEEDED(result)){wchar_t wide[MAX_PATH];MultiByteToWideChar(CP_ACP,0,link_path,-1,wide,MAX_PATH);result=persist->lpVtbl->Save(persist,wide,TRUE);persist->lpVtbl->Release(persist);}link->lpVtbl->Release(link);return SUCCEEDED(result);}
static void close_running_client(void){HWND running=FindWindowExA(HWND_MESSAGE,NULL,"RekaQueueNotifierWindow",NULL);if(running){SendMessageA(running,WM_CLOSE,0,0);Sleep(600);}}
static void register_installed_app(const char *directory,const char *notifier,const char *uninstaller){HKEY key;if(RegCreateKeyExA(HKEY_CURRENT_USER,"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\RekaQueueNotifier",0,NULL,0,KEY_SET_VALUE,NULL,&key,NULL)!=ERROR_SUCCESS)return;char command[MAX_PATH+4];snprintf(command,sizeof(command),"\"%s\"",uninstaller);const char *name="Reka Queue Notifier",*version="1.4.0",*publisher="Sulis Setiyawan - rekakarsa",*website="https://rekadev.site";DWORD one=1,size=2048;RegSetValueExA(key,"DisplayName",0,REG_SZ,(BYTE*)name,(DWORD)strlen(name)+1);RegSetValueExA(key,"DisplayVersion",0,REG_SZ,(BYTE*)version,(DWORD)strlen(version)+1);RegSetValueExA(key,"Publisher",0,REG_SZ,(BYTE*)publisher,(DWORD)strlen(publisher)+1);RegSetValueExA(key,"InstallLocation",0,REG_SZ,(BYTE*)directory,(DWORD)strlen(directory)+1);RegSetValueExA(key,"DisplayIcon",0,REG_SZ,(BYTE*)notifier,(DWORD)strlen(notifier)+1);RegSetValueExA(key,"URLInfoAbout",0,REG_SZ,(BYTE*)website,(DWORD)strlen(website)+1);RegSetValueExA(key,"UninstallString",0,REG_SZ,(BYTE*)command,(DWORD)strlen(command)+1);RegSetValueExA(key,"QuietUninstallString",0,REG_SZ,(BYTE*)command,(DWORD)strlen(command)+1);RegSetValueExA(key,"EstimatedSize",0,REG_DWORD,(BYTE*)&size,sizeof(size));RegSetValueExA(key,"NoModify",0,REG_DWORD,(BYTE*)&one,sizeof(one));RegSetValueExA(key,"NoRepair",0,REG_DWORD,(BYTE*)&one,sizeof(one));RegCloseKey(key);}
int WINAPI WinMain(HINSTANCE instance,HINSTANCE previous,LPSTR command_line,int show){(void)previous;(void)command_line;(void)show;if(MessageBoxA(NULL,"Welcome to Reka Queue Notifier Setup\n\nThis wizard will install the native notification client, add it to Windows startup, and register an uninstaller.\n\nSelect Install to continue.","Reka Queue Notifier Setup",MB_YESNO|MB_ICONINFORMATION|MB_DEFBUTTON1)!=IDYES)return 0;SetCursor(LoadCursor(NULL,IDC_WAIT));CoInitializeEx(NULL,COINIT_APARTMENTTHREADED);char local[MAX_PATH],directory[MAX_PATH],notifier[MAX_PATH],uninstaller[MAX_PATH],ini[MAX_PATH],readme[MAX_PATH];if(!GetEnvironmentVariableA("LOCALAPPDATA",local,sizeof(local))){MessageBoxA(NULL,"LOCALAPPDATA is unavailable.","Installation failed",MB_OK|MB_ICONERROR);return 1;}snprintf(directory,sizeof(directory),"%s\\RekaQueueNotifier",local);CreateDirectoryA(directory,NULL);snprintf(notifier,sizeof(notifier),"%s\\RekaQueueNotifier.exe",directory);snprintf(uninstaller,sizeof(uninstaller),"%s\\Uninstall.exe",directory);snprintf(ini,sizeof(ini),"%s\\reka-notifier.ini",directory);snprintf(readme,sizeof(readme),"%s\\README.txt",directory);close_running_client();if(!extract_resource(instance,RES_NOTIFIER,notifier,0)||!extract_resource(instance,RES_UNINSTALL,uninstaller,0)||!extract_resource(instance,RES_INI,ini,1)||!extract_resource(instance,RES_README,readme,0)){MessageBoxA(NULL,"Unable to write the application files.","Installation failed",MB_OK|MB_ICONERROR);CoUninitialize();return 1;}HKEY run;if(RegCreateKeyExA(HKEY_CURRENT_USER,"Software\\Microsoft\\Windows\\CurrentVersion\\Run",0,NULL,0,KEY_SET_VALUE,NULL,&run,NULL)==ERROR_SUCCESS){char command[MAX_PATH+4];snprintf(command,sizeof(command),"\"%s\"",notifier);RegSetValueExA(run,"RekaQueueNotifier",0,REG_SZ,(BYTE*)command,(DWORD)strlen(command)+1);RegCloseKey(run);}register_installed_app(directory,notifier,uninstaller);char programs[MAX_PATH],link[MAX_PATH];if(SHGetFolderPathA(NULL,CSIDL_PROGRAMS,NULL,SHGFP_TYPE_CURRENT,programs)==S_OK){snprintf(link,sizeof(link),"%s\\Reka Queue Notifier.lnk",programs);create_shortcut(notifier,directory,link,"Open Reka Queue Notifier");}SetCursor(LoadCursor(NULL,IDC_ARROW));MessageBoxA(NULL,"Installation completed successfully.\n\nReka Queue Notifier is now listed in Windows Installed Apps and will start automatically when you sign in.\n\nThe connection wizard will open next.","Setup Complete",MB_OK|MB_ICONINFORMATION);ShellExecuteA(NULL,"open",notifier,NULL,directory,SW_SHOWNORMAL);CoUninitialize();return 0;}
