<div class="page-heading"><div><span class="eyebrow">APLIKASI CLIENT</span><h1>Download Aplikasi</h1><p>Pilih aplikasi sesuai perangkat. Paket Windows bertanda siap pakai otomatis mengikuti alamat server yang sedang Anda akses.</p></div></div>
<div class="client-download-grid">
    <article class="client-download-card complete-client"><div class="client-download-icon">▦</div><div><span>UNTUK KOMPUTER SERVER</span><h2>Windows Server Installer</h2><p>Installer mandiri dengan wizard, database, layanan Windows, firewall, backup, upgrade, dan uninstaller. Tidak memerlukan Docker, XAMPP, atau aplikasi server lain.</p><ul><li>Instalasi Next → Finish</li><li>PHP, Caddy, dan SQLite sudah termasuk</li><li>Data aman saat upgrade atau uninstall</li></ul></div><a class="button" href="/downloads/RekaQueueServerSetup.exe" download>Download Setup EXE</a></article>
    <article class="client-download-card operator-client"><div class="client-download-icon">👤</div><div><span>UNTUK PETUGAS</span><h2>Operator Client</h2><p>Menyimpan sesi perangkat, membuka konsol operator, dan otomatis berjalan bersama Windows.</p><ul><li>Login satu kali</li><li>Sesi perangkat satu tahun</li><li>Startup Windows otomatis</li></ul></div><a class="button" href="/downloads/reka-operator-client.zip" download>Download Operator EXE</a></article>
    <article class="client-download-card operator-client"><div class="client-download-icon">🔔</div><div><span>NOTIFIKASI TANPA BROWSER</span><h2>Windows Notification Client</h2><p>Installer resmi untuk system tray dan notifikasi Windows walaupun tab web ditutup.</p><ul><li>Install dan upgrade otomatis</li><li>Auto-start dan token perangkat aman</li><li>Uninstall dari Windows Settings</li></ul></div><a class="button" href="/downloads/RekaQueueNotifierSetup.exe" download>Download Installer</a></article>
    <article class="client-download-card operator-client"><div class="client-download-icon">A</div><div><span>ANDROID 8+</span><h2>Android Operator &amp; Kiosk</h2><p>Satu APK dengan wizard koneksi server, mode operator, dan kiosk fullscreen tanpa login.</p><ul><li>Server diingat dan status Connected</li><li>Operator dengan notifikasi native</li><li>Kiosk fullscreen otomatis</li></ul></div><a class="button" href="/downloads/RekaQueueNotifier.apk" download>Download Android APK</a></article>
    <article class="client-download-card operator-client"><div class="client-download-icon">L</div><div><span>LINUX CLIENT</span><h2>Linux Notification Client</h2><p>Paket DEB untuk notifikasi antrean pada workstation operator berbasis Linux.</p><ul><li>Service latar belakang</li><li>Konfigurasi server tersimpan</li><li>Terintegrasi dengan akun operator</li></ul></div><a class="button" href="/downloads/reka-queue-notifier-linux.deb" download>Download Linux DEB</a></article>
    <article class="client-download-card display-client"><div class="client-download-icon">▣</div><div><span>UNTUK MONITOR INFORMASI</span><h2>Display Client</h2><p>Membuka display fullscreen pada monitor yang ditentukan dan mempertahankan pemutaran video.</p><ul><li>Tanpa login</li><li>Display key tersimpan</li><li>Posisi monitor tersimpan</li></ul></div><a class="button" href="/downloads/reka-display-client.zip" download>Download Display EXE</a></article>
    <article class="client-download-card kiosk-client"><div class="client-download-icon">▤</div><div><span>UNTUK PINTU MASUK</span><h2>Kiosk &amp; Printer</h2><p>Kiosk fullscreen beserta agent printer thermal untuk mencetak tiket secara langsung.</p><ul><li>Cetak tanpa dialog</li><li>ESC/POS 58 mm</li><li>Startup Windows otomatis</li></ul></div><a class="button" href="/downloads/reka-kiosk-printer.zip" download>Download Kiosk</a></article>
    <article class="client-download-card complete-client"><div class="client-download-icon">⬇</div><div><span>UNTUK ADMINISTRATOR</span><h2>Paket Lengkap</h2><p>Seluruh client, launcher lama, konfigurasi, dan dokumentasi dalam satu paket.</p><ul><li>Operator dan display EXE</li><li>Kiosk dan printer</li><li>Dokumentasi instalasi</li></ul></div><a class="button secondary" href="/downloads/reka-queue-windows-startup.zip" download>Download Semua</a></article>
    <article class="client-download-card complete-client"><div class="client-download-icon">W</div><div><span>UNTUK WEBSITE WORDPRESS</span><h2>Plugin Pendaftaran Online</h2><p>Hubungkan WordPress dengan formulir pendaftaran dan check-in antrean tanpa mengekspos API key.</p><ul><li>Shortcode formulir dan check-in</li><li>Pengaturan koneksi dan test</li><li>Responsive untuk mobile</li></ul></div><a class="button" href="/downloads/reka-queue-online-wordpress.zip" download>Download Plugin</a></article>
</div>
<section class="card client-install-note"><h2>Instalasi singkat</h2><ol><li>Buka halaman ini memakai alamat server yang akan digunakan perangkat, misalnya IP LAN, Tailscale, atau domain publik.</li><li>Download paket lalu pilih <b>Extract All</b>. Alamat server dan display key sudah dimasukkan otomatis ke <b>reka-queue-config.ini</b>.</li><li>Jalankan file EXE. Dengan <b>AUTO_START=1</b>, aplikasi akan dibuka otomatis saat masuk Windows.</li></ol><p><b>Catatan:</b> installer server, Android, Linux, notifier, dan plugin WordPress tetap memakai wizard/login pertama agar aman dan dapat digunakan pada server lain.</p></section>
